name: EC2 Instance Report

on:
  workflow_dispatch:


jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update

      - name: AWS Credentials Configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'ap-south-1'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Generate report
        shell: bash
        run: |
          
           chmod 777 report.sh && aws ec2 describe-instances --filters 'Name=instance-state-name,Values=stopped' --query 'Reservations[].Instances[].{Name:Tags[?Key==`Name`].Value | [0],InstanceId:InstanceId}' --output table
           ./report.sh
           

      # aws ec2 describe-instances --instance-ids --query "Reservations[*].Instances[*].RunningProcesses[].ProcessName" --output text | wc -l
      # - name: copy output into a file
      #   run: | 
      #      echo -e "$instance_details" > instance_details.txt
      # - name: Upload output file
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: instance_details.txt
      #     path: output.txt




