name: EC2 Instance Report

on:
  workflow_dispatch:


jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get update
      - name: Generate report
        run: report.sh

      - name: AWS Credentials Configuration
        uses: aws-actions/configure-aws-credentials@v1
         with:
         aws-region: ap-south-1
         aws-access-key-id: AKIAZQLPN7YWTET2ZAUP
         aws-secret-access-key: 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
         aws-session-token: 
