name: EC2 Instance Report

on:
  workflow_dispatch:


jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update

      - name: AWS Credentials Configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'ap-south-1'
          aws-access-key-id: 'AKIAZQLPN7YWTET2ZAUP'
          aws-secret-access-key: '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'

      - name: Generate report
        # run: report.sh
        shell: bash
        run: |
           aws ec2 describe-instances --filters 'Name=instance-state-name,Values=stopped' --query 'Reservations[].Instances[].{Name:Tags[?Key==`Name`].Value | [0],InstanceId:InstanceId}' --output table
           aws cloudwatch get-metric-statistics --namespace AWS/EC2 --metric-name CPUUtilization  --period 3600 --statistics Maximum --dimensions Name=InstanceId,Value="$Instance_Id"  --start-time 2022-10-18T23:18:00 --end-time 2022-10-19T23:18:00


